name: BuildKernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare env
        run: |
          echo "Prepare..."
          sudo apt update -y
          sudo apt-get install -y zipalign openssl ccache bc bash git-core gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python  m4 gcc libtool zlib1g-dev flex libssl-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi python2
      - name: Pull
        run: |
          echo "拉取Source"
          git clone https://oauth2:$TOKEN@github.com/zclkkk/kernel_xiaomi_sm8250.git --depth=1
          echo "拉取Source完成"
          echo "拉取Toolchain"
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang -b master
          git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
          echo "拉取Toolchain完成"
      - name: Build
        run: |
          echo "开始构建"
          mv build.sh kernel_xiaomi_sm8250/
          cd kernel_xiaomi_sm8250
          bash build.sh
      - name: Upload
        run: |
          echo "Uploading"
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          7z a -mx9 kernel.zip *
          zipalign -v 4 kernel.zip ../kernel.zip
          cd ..
          curl -sL https://git.io/file-transfer | bash -s beta
          ./transfer wet kernel.zip
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: Up
          path: kernel.zip
